{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agm-keycloak.fullname" . }}
  labels:
    {{- include "agm-keycloak.labels" . }}
    component: keycloak
type: Opaque
data:
  admin-password: {{ "changeme" | b64enc | quote }}
  db-password: {{ "changeme" | b64enc | quote }}
{{- end }}
